import { eq, sql } from 'drizzle-orm';
import { ingredients } from './schema.ts';
import type { DietaryTrait } from '../../shared/types.ts';

export interface RawCanonicalIngredient {
  id: string;
  primaryNameEn: string;
  primaryNameDe: string;
  aliases: string[];
  densityGPerMl: number | null;
  defaultTrait: DietaryTrait;
  parentGroupId?: string;
}

export const CANONICAL_INGREDIENTS: RawCanonicalIngredient[] = [
  // Dairy & Alternatives
  {
    id: 'ing_milk',
    primaryNameEn: 'Milk',
    primaryNameDe: 'Milch',
    aliases: ['Milk', 'Cow Milk', 'Vollmilch', 'Milch', "Cow's Milk", 'Kuhmilch'],
    densityGPerMl: 1.03,
    defaultTrait: 'VEGETARIAN',
  },
  {
    id: 'ing_oat_milk',
    primaryNameEn: 'Oat Milk',
    primaryNameDe: 'Hafermilch',
    aliases: ['Oat Milk', 'Oatmilk', 'Hafermilch', 'Haferdrink'],
    densityGPerMl: 1.03,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_milk',
  },
  {
    id: 'ing_almond_milk',
    primaryNameEn: 'Almond Milk',
    primaryNameDe: 'Mandelmilch',
    aliases: ['Almond Milk', 'Mandelmilch', 'Mandeldrink'],
    densityGPerMl: 1.02,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_milk',
  },
  {
    id: 'ing_soy_milk',
    primaryNameEn: 'Soy Milk',
    primaryNameDe: 'Sojamilch',
    aliases: ['Soy Milk', 'Soymilk', 'Sojamilch', 'Sojadrink'],
    densityGPerMl: 1.03,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_milk',
  },
  {
    id: 'ing_heavy_cream',
    primaryNameEn: 'Heavy Cream',
    primaryNameDe: 'Schlagsahne',
    aliases: ['Heavy Cream', 'Whipping Cream', 'Schlagsahne', 'Sahne', 'Double Cream', 'Schlagobers'],
    densityGPerMl: 0.98,
    defaultTrait: 'VEGETARIAN',
    parentGroupId: 'ing_milk',
  },
  {
    id: 'ing_coconut_milk',
    primaryNameEn: 'Coconut Milk',
    primaryNameDe: 'Kokosmilch',
    aliases: ['Coconut Milk', 'Kokosmilch', 'Coconut Cream'],
    densityGPerMl: 0.96,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_milk',
  },
  {
    id: 'ing_butter',
    primaryNameEn: 'Butter',
    primaryNameDe: 'Butter',
    aliases: ['Butter', 'Unsalted Butter', 'Süßrahmbutter', 'Salted Butter', 'Sauerrahmbutter'],
    densityGPerMl: 0.911,
    defaultTrait: 'VEGETARIAN',
  },
  {
    id: 'ing_margarine',
    primaryNameEn: 'Margarine',
    primaryNameDe: 'Margarine',
    aliases: ['Margarine', 'Plant Butter', 'Pflanzencreme', 'Pflanzenmargarine'],
    densityGPerMl: 0.92,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_butter',
  },
  {
    id: 'ing_cheese',
    primaryNameEn: 'Cheese',
    primaryNameDe: 'Käse',
    aliases: ['Cheese', 'Käse', 'Hard Cheese', 'Schnittkäse'],
    densityGPerMl: null,
    defaultTrait: 'VEGETARIAN',
  },
  {
    id: 'ing_cheddar',
    primaryNameEn: 'Cheddar Cheese',
    primaryNameDe: 'Cheddar',
    aliases: ['Cheddar Cheese', 'Cheddar', 'Cheddarkäse'],
    densityGPerMl: null,
    defaultTrait: 'VEGETARIAN',
    parentGroupId: 'ing_cheese',
  },
  {
    id: 'ing_mozzarella',
    primaryNameEn: 'Mozzarella',
    primaryNameDe: 'Mozzarella',
    aliases: ['Mozzarella', 'Fresh Mozzarella', 'Büffelmozzarella'],
    densityGPerMl: null,
    defaultTrait: 'VEGETARIAN',
    parentGroupId: 'ing_cheese',
  },
  {
    id: 'ing_parmesan',
    primaryNameEn: 'Parmesan Cheese',
    primaryNameDe: 'Parmesan',
    aliases: ['Parmesan', 'Parmigiano-Reggiano', 'Hartkäse', 'Parmesankäse'],
    densityGPerMl: null,
    defaultTrait: 'VEGETARIAN',
    parentGroupId: 'ing_cheese',
  },
  {
    id: 'ing_cream_cheese',
    primaryNameEn: 'Cream Cheese',
    primaryNameDe: 'Frischkäse',
    aliases: ['Cream Cheese', 'Frischkäse', 'Double Cream Cheese'],
    densityGPerMl: 1.0,
    defaultTrait: 'VEGETARIAN',
    parentGroupId: 'ing_cheese',
  },
  {
    id: 'ing_yogurt',
    primaryNameEn: 'Yogurt',
    primaryNameDe: 'Joghurt',
    aliases: ['Yogurt', 'Plain Yogurt', 'Joghurt', 'Naturjoghurt'],
    densityGPerMl: 1.04,
    defaultTrait: 'VEGETARIAN',
  },
  {
    id: 'ing_greek_yogurt',
    primaryNameEn: 'Greek Yogurt',
    primaryNameDe: 'Griechischer Joghurt',
    aliases: ['Greek Yogurt', 'Griechischer Joghurt'],
    densityGPerMl: 1.05,
    defaultTrait: 'VEGETARIAN',
    parentGroupId: 'ing_yogurt',
  },
  {
    id: 'ing_sour_cream',
    primaryNameEn: 'Sour Cream',
    primaryNameDe: 'Schmand',
    aliases: ['Sour Cream', 'Schmand', 'Sauerrahm', 'Crème Fraîche'],
    densityGPerMl: 1.01,
    defaultTrait: 'VEGETARIAN',
    parentGroupId: 'ing_milk',
  },
  {
    id: 'ing_egg',
    primaryNameEn: 'Egg',
    primaryNameDe: 'Ei',
    aliases: ['Egg', 'Chicken Egg', 'Ei', 'Eier', 'Large Egg'],
    densityGPerMl: null,
    defaultTrait: 'VEGETARIAN',
  },

  // Flour, Sugar & Bakery Staples
  {
    id: 'ing_flour',
    primaryNameEn: 'All-Purpose Flour',
    primaryNameDe: 'Weizenmehl',
    aliases: ['Flour', 'All-Purpose Flour', 'Weizenmehl', 'Plain Flour', 'Mehl', 'Type 405'],
    densityGPerMl: 0.59,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_bread_flour',
    primaryNameEn: 'Bread Flour',
    primaryNameDe: 'Brotmehl',
    aliases: ['Bread Flour', 'Weizenmehl Type 550', 'Brotmehl'],
    densityGPerMl: 0.59,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_flour',
  },
  {
    id: 'ing_whole_wheat_flour',
    primaryNameEn: 'Whole Wheat Flour',
    primaryNameDe: 'Vollkornmehl',
    aliases: ['Whole Wheat Flour', 'Vollkornmehl', 'Wholemeal Flour'],
    densityGPerMl: 0.55,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_flour',
  },
  {
    id: 'ing_sugar',
    primaryNameEn: 'Granulated Sugar',
    primaryNameDe: 'Zucker',
    aliases: ['Sugar', 'Granulated Sugar', 'Zucker', 'White Sugar', 'Haushaltszucker'],
    densityGPerMl: 0.85,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_brown_sugar',
    primaryNameEn: 'Brown Sugar',
    primaryNameDe: 'Brauner Zucker',
    aliases: ['Brown Sugar', 'Brauner Zucker', 'Rohrzucker', 'Cane Sugar'],
    densityGPerMl: 0.82,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_sugar',
  },
  {
    id: 'ing_powdered_sugar',
    primaryNameEn: 'Powdered Sugar',
    primaryNameDe: 'Puderzucker',
    aliases: ['Powdered Sugar', 'Confectioners Sugar', 'Puderzucker', 'Staubzucker'],
    densityGPerMl: 0.56,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_sugar',
  },
  {
    id: 'ing_salt',
    primaryNameEn: 'Table Salt',
    primaryNameDe: 'Salz',
    aliases: ['Salt', 'Table Salt', 'Salz', 'Sea Salt', 'Kochsalz', 'Meersalz'],
    densityGPerMl: 1.2,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_black_pepper',
    primaryNameEn: 'Black Pepper',
    primaryNameDe: 'Schwarzer Pfeffer',
    aliases: ['Black Pepper', 'Ground Black Pepper', 'Schwarzer Pfeffer', 'Pfeffer'],
    densityGPerMl: 0.5,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_baking_powder',
    primaryNameEn: 'Baking Powder',
    primaryNameDe: 'Backpulver',
    aliases: ['Baking Powder', 'Backpulver'],
    densityGPerMl: 0.9,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_yeast',
    primaryNameEn: 'Dry Yeast',
    primaryNameDe: 'Trockenhefe',
    aliases: ['Yeast', 'Dry Yeast', 'Active Dry Yeast', 'Trockenhefe', 'Hefe'],
    densityGPerMl: 0.6,
    defaultTrait: 'VEGAN',
  },

  // Oils & Fats
  {
    id: 'ing_cooking_oil',
    primaryNameEn: 'Cooking Oil',
    primaryNameDe: 'Speiseöl',
    aliases: ['Cooking Oil', 'Speiseöl', 'Pflanzenöl', 'Vegetable Oil'],
    densityGPerMl: 0.92,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_olive_oil',
    primaryNameEn: 'Olive Oil',
    primaryNameDe: 'Olivenöl',
    aliases: ['Olive Oil', 'Extra Virgin Olive Oil', 'Olivenöl'],
    densityGPerMl: 0.92,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_cooking_oil',
  },
  {
    id: 'ing_sunflower_oil',
    primaryNameEn: 'Sunflower Oil',
    primaryNameDe: 'Sonnenblumenöl',
    aliases: ['Sunflower Oil', 'Sonnenblumenöl'],
    densityGPerMl: 0.92,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_cooking_oil',
  },
  {
    id: 'ing_sesame_oil',
    primaryNameEn: 'Sesame Oil',
    primaryNameDe: 'Sesamöl',
    aliases: ['Sesame Oil', 'Sesamöl'],
    densityGPerMl: 0.92,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_cooking_oil',
  },

  // Grains & Carbohydrates
  {
    id: 'ing_rice',
    primaryNameEn: 'White Rice',
    primaryNameDe: 'Weißer Reis',
    aliases: ['Rice', 'White Rice', 'Reis', 'Weißer Reis', 'Basmati Rice', 'Jasmine Rice'],
    densityGPerMl: 0.85,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_brown_rice',
    primaryNameEn: 'Brown Rice',
    primaryNameDe: 'Naturreis',
    aliases: ['Brown Rice', 'Naturreis', 'Vollkornreis'],
    densityGPerMl: 0.85,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_rice',
  },
  {
    id: 'ing_oats',
    primaryNameEn: 'Rolled Oats',
    primaryNameDe: 'Haferflocken',
    aliases: ['Oats', 'Rolled Oats', 'Haferflocken', 'Oatmeal'],
    densityGPerMl: 0.41,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_pasta',
    primaryNameEn: 'Pasta',
    primaryNameDe: 'Nudeln',
    aliases: ['Pasta', 'Nudeln', 'Spaghetti', 'Penne', 'Teigwaren'],
    densityGPerMl: 0.5,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_bread',
    primaryNameEn: 'White Bread',
    primaryNameDe: 'Weissbrot',
    aliases: ['Bread', 'White Bread', 'Brot', 'Toastbrot', 'Weissbrot'],
    densityGPerMl: null,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_breadcrumbs',
    primaryNameEn: 'Breadcrumbs',
    primaryNameDe: 'Paniermehl',
    aliases: ['Breadcrumbs', 'Paniermehl', 'Panko', 'Semmelbrösel'],
    densityGPerMl: 0.45,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_bread',
  },

  // Vegetables & Produce
  {
    id: 'ing_onion',
    primaryNameEn: 'Yellow Onion',
    primaryNameDe: 'Zwiebel',
    aliases: ['Onion', 'Yellow Onion', 'Zwiebel', 'Gemüsezwiebel'],
    densityGPerMl: 0.65,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_red_onion',
    primaryNameEn: 'Red Onion',
    primaryNameDe: 'Rote Zwiebel',
    aliases: ['Red Onion', 'Rote Zwiebel'],
    densityGPerMl: 0.65,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_onion',
  },
  {
    id: 'ing_garlic',
    primaryNameEn: 'Garlic',
    primaryNameDe: 'Knoblauch',
    aliases: ['Garlic', 'Garlic Clove', 'Knoblauch', 'Knoblauchzehe'],
    densityGPerMl: 0.6,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_tomato',
    primaryNameEn: 'Tomato',
    primaryNameDe: 'Tomate',
    aliases: ['Tomato', 'Tomate', 'Roma Tomato', 'Cherry Tomato'],
    densityGPerMl: 0.7,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_canned_tomatoes',
    primaryNameEn: 'Canned Tomatoes',
    primaryNameDe: 'Dosen-Tomaten',
    aliases: ['Canned Tomatoes', 'Diced Tomatoes', 'Stückige Tomaten', 'Dopentomaten', 'Passierte Tomaten'],
    densityGPerMl: 1.0,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_tomato',
  },
  {
    id: 'ing_potato',
    primaryNameEn: 'Potato',
    primaryNameDe: 'Kartoffel',
    aliases: ['Potato', 'Kartoffel', 'Kartoffeln', 'Russet Potato'],
    densityGPerMl: 0.75,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_sweet_potato',
    primaryNameEn: 'Sweet Potato',
    primaryNameDe: 'Süßkartoffel',
    aliases: ['Sweet Potato', 'Süßkartoffel'],
    densityGPerMl: 0.7,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_potato',
  },
  {
    id: 'ing_carrot',
    primaryNameEn: 'Carrot',
    primaryNameDe: 'Karotte',
    aliases: ['Carrot', 'Karotte', 'Möhre', 'Möhren'],
    densityGPerMl: 0.64,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_bell_pepper',
    primaryNameEn: 'Bell Pepper',
    primaryNameDe: 'Paprikaschote',
    aliases: ['Bell Pepper', 'Paprika', 'Paprikaschote', 'Sweet Pepper'],
    densityGPerMl: 0.5,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_broccoli',
    primaryNameEn: 'Broccoli',
    primaryNameDe: 'Brokkoli',
    aliases: ['Broccoli', 'Brokkoli'],
    densityGPerMl: 0.35,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_spinach',
    primaryNameEn: 'Spinach',
    primaryNameDe: 'Spinat',
    aliases: ['Spinach', 'Fresh Spinach', 'Spinat', 'Blattspinat'],
    densityGPerMl: 0.2,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_zucchini',
    primaryNameEn: 'Zucchini',
    primaryNameDe: 'Zucchini',
    aliases: ['Zucchini', 'Courgette'],
    densityGPerMl: 0.6,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_cucumber',
    primaryNameEn: 'Cucumber',
    primaryNameDe: 'Gurke',
    aliases: ['Cucumber', 'Gurke', 'Salatgurke'],
    densityGPerMl: 0.65,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_mushroom',
    primaryNameEn: 'Button Mushroom',
    primaryNameDe: 'Champignon',
    aliases: ['Mushroom', 'Champignon', 'Button Mushroom', 'Pilze'],
    densityGPerMl: 0.35,
    defaultTrait: 'VEGAN',
  },

  // Fruits
  {
    id: 'ing_apple',
    primaryNameEn: 'Apple',
    primaryNameDe: 'Apfel',
    aliases: ['Apple', 'Apfel', 'Äpfel'],
    densityGPerMl: 0.6,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_banana',
    primaryNameEn: 'Banana',
    primaryNameDe: 'Banane',
    aliases: ['Banana', 'Banane', 'Bananen'],
    densityGPerMl: 0.6,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_lemon',
    primaryNameEn: 'Lemon',
    primaryNameDe: 'Zitrone',
    aliases: ['Lemon', 'Zitrone', 'Lemon Juice', 'Zitronensaft'],
    densityGPerMl: 0.95,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_lime',
    primaryNameEn: 'Lime',
    primaryNameDe: 'Limette',
    aliases: ['Lime', 'Limette', 'Lime Juice', 'Limetten-Saft'],
    densityGPerMl: 0.95,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_lemon',
  },
  {
    id: 'ing_strawberry',
    primaryNameEn: 'Strawberry',
    primaryNameDe: 'Erdbeere',
    aliases: ['Strawberry', 'Erdbeere', 'Erdbeeren'],
    densityGPerMl: 0.6,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_avocado',
    primaryNameEn: 'Avocado',
    primaryNameDe: 'Avocado',
    aliases: ['Avocado', 'Avocados'],
    densityGPerMl: 0.9,
    defaultTrait: 'VEGAN',
  },

  // Meats & Seafood
  {
    id: 'ing_poultry',
    primaryNameEn: 'Poultry Meat',
    primaryNameDe: 'Geflügelfleisch',
    aliases: ['Poultry', 'Poultry Meat', 'Geflügel', 'Geflügelfleisch'],
    densityGPerMl: 1.0,
    defaultTrait: 'OMNIVORE',
  },
  {
    id: 'ing_chicken_breast',
    primaryNameEn: 'Chicken Breast',
    primaryNameDe: 'Hähnchenbrust',
    aliases: ['Chicken Breast', 'Hähnchenbrust', 'Chicken', 'Hühnerbrust', 'Hähnchen'],
    densityGPerMl: 1.0,
    defaultTrait: 'OMNIVORE',
    parentGroupId: 'ing_poultry',
  },
  {
    id: 'ing_ground_beef',
    primaryNameEn: 'Ground Beef',
    primaryNameDe: 'Rinderhackfleisch',
    aliases: ['Ground Beef', 'Minced Beef', 'Rinderhackfleisch', 'Hackfleisch', 'Beef Mince'],
    densityGPerMl: 0.95,
    defaultTrait: 'OMNIVORE',
  },
  {
    id: 'ing_pork_chop',
    primaryNameEn: 'Pork Chop',
    primaryNameDe: 'Schweinekotelett',
    aliases: ['Pork Chop', 'Schweinekotelett', 'Pork', 'Schweinefleisch'],
    densityGPerMl: 1.0,
    defaultTrait: 'OMNIVORE',
  },
  {
    id: 'ing_bacon',
    primaryNameEn: 'Bacon',
    primaryNameDe: 'Speck',
    aliases: ['Bacon', 'Speck', 'Frühstücksspeck', 'Bacon Strips'],
    densityGPerMl: 0.95,
    defaultTrait: 'OMNIVORE',
  },
  {
    id: 'ing_salmon',
    primaryNameEn: 'Salmon Fillet',
    primaryNameDe: 'Lachsfilet',
    aliases: ['Salmon', 'Salmon Fillet', 'Lachs', 'Lachsfilet'],
    densityGPerMl: 1.0,
    defaultTrait: 'OMNIVORE',
  },
  {
    id: 'ing_tuna',
    primaryNameEn: 'Canned Tuna',
    primaryNameDe: 'Thunfisch',
    aliases: ['Tuna', 'Canned Tuna', 'Thunfisch', 'Thunfischdose'],
    densityGPerMl: 1.0,
    defaultTrait: 'OMNIVORE',
  },

  // Legumes, Nuts & Condiments
  {
    id: 'ing_chickpeas',
    primaryNameEn: 'Chickpeas',
    primaryNameDe: 'Kichererbsen',
    aliases: ['Chickpeas', 'Garbanzo Beans', 'Kichererbsen'],
    densityGPerMl: 0.75,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_tofu',
    primaryNameEn: 'Tofu',
    primaryNameDe: 'Tofu',
    aliases: ['Tofu', 'Firm Tofu', 'Silken Tofu', 'Naturtofu'],
    densityGPerMl: 0.95,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_almonds',
    primaryNameEn: 'Almonds',
    primaryNameDe: 'Mandeln',
    aliases: ['Almonds', 'Mandeln', 'Whole Almonds'],
    densityGPerMl: 0.6,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_peanut_butter',
    primaryNameEn: 'Peanut Butter',
    primaryNameDe: 'Erdnussbutter',
    aliases: ['Peanut Butter', 'Erdnussbutter', 'Erdnussmus'],
    densityGPerMl: 1.05,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_soy_sauce',
    primaryNameEn: 'Soy Sauce',
    primaryNameDe: 'Sojasauce',
    aliases: ['Soy Sauce', 'Sojasauce', 'Shoyu', 'Tamari'],
    densityGPerMl: 1.15,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_honey',
    primaryNameEn: 'Honey',
    primaryNameDe: 'Honig',
    aliases: ['Honey', 'Honig', 'Blütenhonig'],
    densityGPerMl: 1.42,
    defaultTrait: 'VEGETARIAN',
  },
  {
    id: 'ing_maple_syrup',
    primaryNameEn: 'Maple Syrup',
    primaryNameDe: 'Ahornsirup',
    aliases: ['Maple Syrup', 'Ahornsirup'],
    densityGPerMl: 1.37,
    defaultTrait: 'VEGAN',
    parentGroupId: 'ing_honey',
  },
  {
    id: 'ing_mustard',
    primaryNameEn: 'Mustard',
    primaryNameDe: 'Senf',
    aliases: ['Mustard', 'Senf', 'Mittelscharfer Senf'],
    densityGPerMl: 1.05,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_mayonnaise',
    primaryNameEn: 'Mayonnaise',
    primaryNameDe: 'Mayonnaise',
    aliases: ['Mayonnaise', 'Mayo'],
    densityGPerMl: 0.92,
    defaultTrait: 'VEGETARIAN',
  },
  {
    id: 'ing_vinegar',
    primaryNameEn: 'White Vinegar',
    primaryNameDe: 'Essig',
    aliases: ['Vinegar', 'White Vinegar', 'Essig', 'Tafelessig'],
    densityGPerMl: 1.01,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_vegetable_broth',
    primaryNameEn: 'Vegetable Broth',
    primaryNameDe: 'Gemüsebrühe',
    aliases: ['Vegetable Broth', 'Vegetable Stock', 'Gemüsebrühe', 'Gemüsefond'],
    densityGPerMl: 1.0,
    defaultTrait: 'VEGAN',
  },
  {
    id: 'ing_chicken_broth',
    primaryNameEn: 'Chicken Broth',
    primaryNameDe: 'Hühnerbrühe',
    aliases: ['Chicken Broth', 'Chicken Stock', 'Hühnerbrühe', 'Geflügelfond'],
    densityGPerMl: 1.0,
    defaultTrait: 'OMNIVORE',
    parentGroupId: 'ing_vegetable_broth',
  },
  {
    id: 'ing_water',
    primaryNameEn: 'Water',
    primaryNameDe: 'Wasser',
    aliases: ['Water', 'Wasser', 'Tap Water', 'Trinkwasser'],
    densityGPerMl: 1.0,
    defaultTrait: 'VEGAN',
  },
];

export async function seedIngredients(dbInstance: any) {
  const pass1Values = CANONICAL_INGREDIENTS.map((item) => ({
    id: item.id,
    primaryNameEn: item.primaryNameEn,
    primaryNameDe: item.primaryNameDe,
    aliasesJson: JSON.stringify(item.aliases),
    densityGPerMl: item.densityGPerMl,
    defaultTrait: item.defaultTrait,
    parentGroupId: null,
  }));

  // Bulk Pass 1: Upsert all ingredients without parentGroupId
  await dbInstance
    .insert(ingredients)
    .values(pass1Values)
    .onConflictDoUpdate({
      target: ingredients.id,
      set: {
        primaryNameEn: sql`excluded.primary_name_en`,
        primaryNameDe: sql`excluded.primary_name_de`,
        aliasesJson: sql`excluded.aliases_json`,
        densityGPerMl: sql`excluded.density_g_per_ml`,
        defaultTrait: sql`excluded.default_trait`,
      },
    });

  // Pass 2: Set parentGroupId for items with parent link inside atomic transaction
  const itemsWithParent = CANONICAL_INGREDIENTS.filter((i) => i.parentGroupId);
  if (itemsWithParent.length > 0) {
    for (const item of itemsWithParent) {
      await dbInstance
        .update(ingredients)
        .set({ parentGroupId: item.parentGroupId })
        .where(eq(ingredients.id, item.id));
    }
  }
}
